### ISSUE TITLE
Please do not include external libraries

### ISSUE THREAD

**Issue by pcav** [gis-support/gis-support-plugin#4]
better have them added to installers for the OS who need it
thanks

**Comment by gis-support** [comment]
Hi Paolo,
Thanks for your feedback. On pyqtgraph, with first versions we used matplotlib for graphs, but it seems that this library isn't included in all instalators. I'm talking about osgeo4w installer, when user check only qgis in list. So we check how this is done in other plugins and some of them are including this library with source code (like [Profile Tool](https://github.com/PANOimagen/profiletool) has pyqtgraph and dxwriter, [RasterDataPlotting](https://bitbucket.org/janzandr/rasterdataplotting/src/master/rasterdataplotting/site/pyqtgraph/) also includes pyqtgraph), so we do that also. 

I know that since QGIS 3.6 there is possibility to define python dependencies but many people still using 3.4 LTR, and they have to do it manually and most of them don't have knowledge/skills how to do it.

**Comment by pcav** [comment]
Yes, I'm fully aware of the issue, a nssty one. Our preferred solution is to add the necessary libs to the installer, unless they are relly too niche, which does not seem the case here.

**Comment by gis-support** [comment]
We removed pyqtgraph lib and back to matplotlib. I've uploaded new version to QGIS repository after all requested fixes.
